DROP TABLE IF EXISTS schedule;
DROP TABLE IF EXISTS post;

CREATE TABLE schedule (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  movie_title TEXT NOT NULL,
  date VARCHAR NOT NULL,
  time VARCHAR NOT NULL,
  movie_link VARCHAR
);

/* CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
); */

